#Gradle
org.gradle.jvmargs=-Xmx2048M -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx2048M"
org.gradle.caching=true
org.gradle.configuration-cache=true

#Kotlin
kotlin.code.style=official

#Android
android.useAndroidX=true
android.nonTransitiveRClass=true

# Publishing
GROUP=io.noties.kojson
VERSION_NAME=1.0.0-SNAPSHOT
POM_NAME=KoJSON
POM_DESCRIPTION=Opinionated multiplatform JSON facade with pluggable implementations.
POM_INCEPTION_YEAR=2025
POM_URL=https://github.com/noties/KoJSON
POM_SCM_URL=https://github.com/noties/KoJSON
POM_SCM_CONNECTION=scm:git:git://github.com/noties/KoJSON.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com:noties/KoJSON.git
POM_LICENSE_NAME=Apache License, Version 2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENSE_DIST=repo
POM_DEVELOPER_ID=noties
POM_DEVELOPER_NAME=Dmitrii Ivanov
POM_DEVELOPER_EMAIL=inbox@noties.io
