[versions]
agp = "8.13.1"
kotlin = "2.2.21"
jetbrainsKotlinJvm = "2.2.21"
gson = "2.13.2"
# does not follow kotlin versioning
koltinx-serialization = "1.9.0"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
# https://github.com/google/gson
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
# https://github.com/Kotlin/kotlinx.serialization
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "koltinx-serialization" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
vanniktechMavenPublish = { id = "com.vanniktech.maven.publish", version = "0.35.0" }
